---
- name: Load state data to variables
  include_vars:
    file: "{{ vcd_state_file }}"
    name: state_data

- name: Set id
  set_fact:
    state_id: "{{ vcd_state_file | splitext | first | basename  }}"

- name: Set host_groups
  set_fact:
    host_groups: |
      {%- set hostGroups = {} -%}
      {%- for v in state_data.instances -%}
        {%- for g in v.host_groups|default([]) -%}
          {%- if hostGroups[g] is not defined -%}
            {%- set _ = hostGroups.update({g:[]}) -%}
          {%- endif -%}
          {%- set _ = hostGroups[g].append(v.hostname) -%}
        {%- endfor -%}
      {%- endfor -%}
      {{ hostGroups }}

- name: Create inventory group_vars dir
  file:
    path: "{{ inventories_dir }}/vcd-{{ state_id }}/group_vars/all"
    state: directory
    mode: "0755"
    recurse: true

- name: Copy init variables
  file:
    src: "../../../../variables/init.yml"
    dest: "{{ inventories_dir }}/vcd-{{ state_id }}/group_vars/all/init.yml"
    state: link

- name: Create inventory group_vars default all.yml
  file:
    path: "{{ inventories_dir }}/vcd-{{ state_id }}/group_vars/all/all.yml"
    state: touch
    mode: "0655"

- name: Create inventory host_vars dir
  file:
    path: "{{ inventories_dir }}/vcd-{{ state_id }}/host_vars/{{ item.hostname }}"
    state: directory
    mode: "0755"
    recurse: true
  loop: "{{ state_data.instances | default([]) }}"

- name: "Create inventory hosts"
  template:
    src: "vcd-inventory.ini.j2"
    dest: "{{ inventories_dir }}/vcd-{{ state_id }}/hosts"
    mode: "0655"

- name: "Create generated host vars"
  template:
    src: "generated-host-vars.yml.j2"
    dest: "{{ inventories_dir }}/vcd-{{ state_id }}/host_vars/{{ item.hostname }}/generated.yml"
    mode: "0655"
  loop: "{{ state_data.instances | default([]) }}"
