#cloud-config
apt:
  primary:
    - arches: [default]
      uri: http://id.archive.ubuntu.com/ubuntu/

package_update: true
hostname: ${hostname}
ssh_pwauth: false

users:
  -  name: ${local_admin_username}
     lock_passwd: False
     gecos: "Local Admin"
     groups: [adm, audio, cdrom, dialout, dip, floppy, lxd, netdev, plugdev, sudo, video]
     sudo: "ALL=(ALL) NOPASSWD:ALL"
     shell: /bin/bash
     ssh_authorized_keys: 
      - ${local_admin_authorized_key}

  -  name: ${automation_username}
     lock_passwd: False
     gecos: "Automation"
     groups: [adm, audio, cdrom, dialout, dip, floppy, lxd, netdev, plugdev, sudo, video]
     sudo: "ALL=(ALL) NOPASSWD:ALL"
     shell: /bin/bash
     ssh_authorized_keys:
       - ${automation_authorized_key}