---
- name: Copy shh key
  become: true
  copy:
    src: "../.private/ssh-keys/{{ init_local_admin_username }}"
    dest: "/home/{{ init_local_admin_username }}/.ssh/id_rsa"
    owner: "{{ init_local_admin_username }}"
    group: "{{ init_local_admin_username }}"
    mode: "0600"
