---
- name: Docker Install
  hosts: all
  become: true
  tasks:
    - name: Block Install
      when: init_docker_users is defined
      block:
        - name: Install Docker
          ansible.builtin.include_role:
            name: geerlingguy.docker
          vars:
            docker_user: "{{ init_docker_users }}"
        - name: Install Additional Packages
          ansible.builtin.apt:
            pkg:
              - python3-pip
            state: present
        - name: Install docker-py
          ansible.builtin.pip:
            name:
              - docker
            state: present
