---
- name: DSwarm Disks
  hosts: all
  become: true
  tasks:
    - name: Master host disk local /dev/sdb
      when:
        - inventory_hostname in groups['master']
        - "'sdb' in ansible_devices.keys()|list"
      block:
        - name: Create partition /dev/sdb
          community.general.parted:
            device: /dev/sdb
            number: 1
            state: present
        - name: Crate filesystem /dev/sdb1
          community.general.filesystem:
            fstype: ext4
            dev: /dev/sdb1
            state: present
        - name: Create /mnt/local directory
          ansible.builtin.file:
            path: /mnt/local
            state: directory
            mode: "0755"
            owner: "root"
            group: "root"
        - name: Create fstab mount /dev/sdb1
          ansible.posix.mount:
            path: "/mnt/local"
            src: "/dev/sdb1"
            fstype: ext4
            state: present
            boot: true
        - name: Mount /dev/sdb1
          ansible.posix.mount:
            path: "/mnt/local"
            src: "/dev/sdb1"
            fstype: ext4
            state: mounted

    - name: Install nfs packages
      ansible.builtin.apt:
        pkg:
          - nfs-common
        state: present
    - name: Create fstab NAS data-pool
      ansible.posix.mount:
        src: "{{ init_nas_data_pool_fullpath }}"
        path: /mnt/data
        opts: vers=4
        state: present
        fstype: nfs
    - name: Mount NAS data-pool
      ansible.posix.mount:
        src: "{{ init_nas_data_pool_fullpath }}"
        path: /mnt/data
        opts: vers=4
        state: mounted
        fstype: nfs
