---
- name: DSwarm Configure
  hosts: all
  vars:
    master_ip: "{{ hostvars['master']['access_ip'] }}"
    host_access_ip: "{{ hostvars[inventory_hostname]['access_ip'] }}"
    join_tokens: "{{ hostvars['master']['__output_swarm']['swarm_facts']['JoinTokens'] }}"

  tasks:
    - name: Check/Init swarm
      community.docker.docker_swarm:
        state: present
        advertise_addr: "{{ host_access_ip }}"
        default_addr_pool: "{{ init_docker_swarm_default_addr_pool }}"
      register: __output_swarm
      when: inventory_hostname in 'master'

    - name: Configure manager
      community.docker.docker_swarm:
        state: join
        timeout: 60
        advertise_addr: "{{ host_access_ip }}"
        join_token: "{{ join_tokens['Manager'] }}"
        remote_addrs: ["{{ master_ip }}:2377"]
      when:
        - "'managers' in groups"
        - inventory_hostname in groups['managers']

    - name: Configure worker
      community.docker.docker_swarm:
        state: join
        timeout: 60
        advertise_addr: "{{ host_access_ip }}"
        join_token: "{{ join_tokens['Worker'] }}"
        remote_addrs: ["{{ master_ip }}:2377"]
      when: inventory_hostname in groups['workers']

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ hostvars['master']['__output_swarm'] }}"
      when: inventory_hostname in 'master'
